server:
  port: 8002

#服务名
spring:
  application:
    name: service-oss
  #环境设置：dev、test、prod
  profiles:
    active: dev
  #阿里云 OSS
  #不同的服务器，地址不同
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

aliyun:
  oss:
    file:
      endpoint: your endpoint
      keyid: your accessKeyId
      keysecret: your accessKeySecret
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: guli-file



